from shared import Card, load_set


MY_CARDS: dict[str, list[str]] = {
    "9ed": [
        "Foul Imp",
        "Hollow Dogs",
        "Nekrataal",
        "Phyrexian Gargantua",
        "Raise Dead",
        "Serpent Warrior",
        "Unholy Strength",
        "Tanglebloom",
        "Phyrexian Hulk",
    ],
    "rav": [
        "Terraformer",
        "Vedalken Dismisser",
    ],
    "dis": [
        "Helium Squirter",
        "Writ of Passage",
    ],
    "csp": [
        "Frozen Solid",
        "Krovikan Mist",
    ],
    "tsp": [
        "Drifter il-Dal",
        "Fathom Seer",
        "Mystical Teachings",
        "Snapback",
        "Feebleness",
        "Mana Skimmer",
        "Strangling Soot",
        "Durkwood Baloth",
        "Glass Asp",
        "Havenwood Wurm",
        "Herd Gnarr",
        "Molder",
        "Penumbra Spider",
        "Scarwood Treefolk",
        "Thrill of the Hunt",
    ],
    "plc": [
        "Ghost Tactician",
        "Heroes Remembered",
        "Sunlance",
        "Aquamorph Entity",
        "Shaper Parasite",
        "Gossamer Phantasm",
        "Riptide Pilferer",
        "Brain Gorgers",
        "Cradle to Grave",
        "Midnight Charm",
        "Evolution Charm",
        "Mire Boa",
        "Uktabi Drake",
        "Utopia Vow",
        "Urborg, Tomb of Yawgmoth",
    ],
    "fut": [
        "Aven Augur",
        "Leaden Fists",
        "Augur of Skulls",
        "Ichor Slick",
        "Kavu Primarch",
        "Llanowar Augur",
        "Petrified Plating",
        "Quiet Disrepair",
        "Wrap in Vigor",
    ],
    "10e": [
        "Ancestor's Chosen",
        "Angelic Blessing",
        "Condemn",
        "Aven Windreader",
        "Cancel",
        "Crafty Pathmage",
        "Dehydration",
        "Peek",
        "Persuasion",
        "Shimmering Wings",
        "Snapping Drake",
        "Twincast",
        "Afflict",
        "Consume Spirit",
        "Contaminated Bond",
        "Dross Crocodile",
        "Drudge Skeletons",
        "Essence Drain",
        "Fear",
        "Festering Goblin",
        "Gravedigger",
        "Highway Robber",
        "Nightmare",
        "Ravenous Rats",
        "Recover",
        "Severed Legion",
        "Underworld Dreams",
        "Vampire Bats",
        "Goblin Elite Infantry",
        "Goblin Piker",
        "Hill Giant",
        "Incinerate",
        "Lava Axe",
        "Prodigal Pyromancer",
        "Viashino Runner",
        "Aggressive Urge",
        "Civic Wayfinder",
        "Commune with Nature",
        "Elvish Piper",
        "Giant Growth",
        "Giant Spider",
        "Grizzly Bears",
        "Hunted Wumpus",
        "Llanowar Elves",
        "Might Weaver",
        "Natural Spring",
        "Overrun",
        "Rampant Growth",
        "Rootwalla",
        "Seedborn Muse",
        "Spined Wurm",
        "Stalking Tiger",
        "Tangle Spider",
        "Treetop Bracers",
        "Angel's Feather",
        "Demon's Horn",
        "Kraken's Eye",
        "Platinum Angel",
    ],
    "lrw": [
        "Mulldrifter",
        "Boggart Birth Rite",
        "Boggart Harbinger",
        "Boggart Mob",
        "Exiled Boggart",
        "Facevaulter",
        "Fodder Launch",
        "Ghostly Changeling",
        "Hoarder's Greed",
        "Hornet Harasser",
        "Mad Auntie",
        "Marsh Flitter",
        "Spiderwig Boggart",
        "Squeaking Pie Sneak",
        "Warren Pilferers",
        "Adder-Staff Boggart",
        "Boggart Shenanigans",
        "Goatnapper",
        "Lowland Oaf",
        "Mudbutton Torchrunner",
        "Tar Pitcher",
        "Tarfire",
        "Changeling Titan",
        "Shimmering Grotto",
    ],
    "shm": [
        "Barrenton Medic",
        "Boon Reflection",
        "Goldenglow Moth",
        "Mistmeadow Skulk",
        "Woeleecher",
        "Briarberry Cohort",
        "Cerulean Wisps",
        "Consign to Dream",
        "Flow of Ideas",
        "Knacksaw Clique",
        "Prismwake Merrow",
        "Whimwader",
        "Blowfly Infestation",
        "Cinderbones",
        "Crowd of Cinders",
        "Smolder Initiate",
        "Blistering Dieflyn",
        "Boggart Arsonists",
        "Crimson Wisps",
        "Ember Gale",
        "Flame Javelin",
        "Power of Fire",
        "Smash to Smithereens",
        "Crabapple Cohort",
        "Drove of Elves",
        "Gloomwidow's Feast",
        "Juvenile Gloomwidow",
        "Roughshod Mentor",
        "Viridescent Wisps",
        "Curse of Chains",
        "Plumeveil",
        "Somnomancer",
        "Steel of the Godhead",
        "Thistledown Duo",
        "Turn to Mist",
        "Dream Salvage",
        "Gravelgill Axeshark",
        "Helm of the Ghastlord",
        "Scarscale Ritual",
        "Torpor Dust",
        "Cultbrand Cinder",
        "Emberstrike Duo",
        "Kulrath Knight",
        "Sootstoke Kindler",
        "Boggart Ram-Gang",
        "Giantbaiting",
        "Manamorphose",
        "Morselhoarder",
        "Tattermunge Maniac",
        "Vexing Shusher",
        "Mercy Killing",
        "Shield of the Oversoul",
        "Blazethorn Scarecrow",
        "Blight Sickle",
        "Elsewhere Flask",
        "Revelsong Horn",
        "Wingrattle Scarecrow",
    ],
    "eve": [
        "Dream Thief",
        "Rekindled Flame",
        "Duskdale Wurm",
        "Clout of the Dominus",
        "Crackleburr",
        "Crag Puca",
        "Inside Out",
        "Mindwrack Liege",
        "Noggle Bandit",
        "Noggle Hedge-Mage",
        "Nucklavee",
        "Riverfall Mimic",
        "Shrewd Hatchling",
        "Stream Hopper",
        "Fire at Will",
        "Cascade Bluffs",
    ],
    "ala": [
        "Cancel",
        "Manaplasm",
    ],
}


def load_my_cards() -> list[Card]:
    out = []

    for set_id, card_titles in MY_CARDS.items():
        set_cards = load_set(set_id)
        found = set()

        for card in set_cards:
            if card.title in card_titles:
                found.add(card.title)

                out.append(card)

        if set(card_titles) != found:
            raise ValueError(f"Card(s) {set(card_titles) - found} not found")

    return out
